### ISSUE TITLE
Application dies right after start

### ISSUE THREAD

**Issue by ntjn** [jirutka/ldap-passwd-webui#13]
Got this traceback:

> 2018-02-28 09:01:27,720 INFO: Starting ldap-passwd-webui 2.0.0
> Traceback (most recent call last):
>   File "app.py", line 144, in <module>
>     SimpleTemplate.defaults = dict(CONF['html'])
>   File "/usr/lib/python3.6/configparser.py", line 959, in __getitem__
>     raise KeyError(key)
> KeyError: 'html'

Python version: 3.6.4

**Comment by jirutka** [comment]
This (obviously) means that you don’t have `[html]` section in the config file.

**Comment by JonathonReinhart** [comment]
This (also) can mean that that `ConfigParser` doesn't see your ini file.

It really depends how you're running the app, but on `alpine`, this works:
```
# apk add ldap-passwd-webui-waitress
# cd /usr/share/webapps/ldap-passwd-webui
# CONF_FILE=/etc/ldap-passwd-webui.ini waitress-serve app:application
```
