### ISSUE TITLE
I got a erro

### ISSUE THREAD

**Issue by liaoqiArno** [jirutka/ldap-passwd-webui#16]
[root@localhost ldap-passwd-webui]# pip install -r requirements.txt
Ignoring configparser: markers 'python_version < "3.3"' don't match your environment
Requirement already satisfied: bottle>=0.12.8 in /opt/anaconda3/lib/python3.6/site-packages (from -r requirements.txt (line 1)) (0.12.13)
Requirement already satisfied: ldap3<3.0,>=2.0 in /opt/anaconda3/lib/python3.6/site-packages (from -r requirements.txt (line 2)) (2.5)
Requirement already satisfied: pyasn1>=0.1.8 in /opt/anaconda3/lib/python3.6/site-packages (from ldap3<3.0,>=2.0->-r requirements.txt (line 2)) (0.4.3)
[root@localhost ldap-passwd-webui]# pip install bottle
Requirement already satisfied: bottle in /opt/anaconda3/lib/python3.6/site-packages (0.12.13)
[root@localhost ldap-passwd-webui]# python app.py 
2018-05-30 02:03:06,634 INFO: Starting ldap-passwd-webui 2.0.0
Traceback (most recent call last):
  File "app.py", line 144, in <module>
    SimpleTemplate.defaults = dict(CONF['html'])
  File "/opt/anaconda3/lib/python3.6/configparser.py", line 959, in __getitem__
    raise KeyError(key)
KeyError: 'html'

Can you hele me?

**Comment by liaoqiArno** [comment]
my OS is centos7

**Comment by bobocharbo** [comment]
Take a look at the issue just preceding yours:

https://github.com/jirutka/ldap-passwd-webui/issues/13
